name: Run modelsim_configure.py and Push Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true # Allows push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies here, e.g., pip install -r requirements.txt

      - name: Run Python script
        run: python modelsim_configure.py
        working-directory: Processor/

      - name: Configure git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Stage changes
        run: git add .
 
      - name: Commit changes
        run: |
          git diff-index --quiet HEAD || git commit -m "Automated commit from GitHub Actions"

      - name: Stash changes if necessary
        run: |
          git stash || echo "No stash entries found."

      - name: Pull latest changes from GitHub
        run: git pull --rebase origin ${{ github.ref }}

      - name: Pop stash if necessary
        run: |
          git stash pop || echo "No stash entries found."

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}